version: 2

models:
  - name: fact_bike_trips
    description: >
      fact bike data

  - name: dim_bike_types
    description: bike types
  
  - name: dim_bike_membership
    description: membershio subscription
  

